const url = 'https://njdpusudnfbmdtyxymsc.supabase.co/rest/v1/profiles?select=id%2Cusername%2Cavatar_url%2Creputation_score%2Csales_count%2Clast_seen_at&order=created_at.desc.nullslast&limit=5';
const headers = {
    'accept': '*/*',
    'apikey': 'sb_publishable_AuuUPxndmozJ9jOo2U0txA_vipT8SOr',
    'authorization': 'Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjdhMmQzZDQyLTMwODktNDUyNi04ZGM3LTFiNWZiZjgxOTRiYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL25qZHB1c3VkbmZibWR0eXh5bXNjLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwZTA2M2UwNC1iOGU0LTQ4MDctYjFkZi0zZDIwZTRhYzBjNTIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzcyNzM3NTU2LCJpYXQiOjE3NzI3MzM5NTYsImVtYWlsIjoibWFyY2Vsby5sZW1wZWtAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnb29nbGUiLCJwcm92aWRlcnMiOlsiZ29vZ2xlIl19LCJ1c2VyX21ldGFkYXRhIjp7ImFjdGl2ZV90ZW5hbnRfaWQiOiJlMTU1MjQ1NC0wYTlkLTQ3ZWEtODYzYS1hNDA1NzMxNmU1MDIiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTEtqYTlGY2hnWHlNOG1CUThXWGNDNmEzSzJ5VU9zY2EwaXFYUFU4QzhNNi1WT1E5SlNDUT1zOTYtYyIsImVtYWlsIjoibWFyY2Vsby5sZW1wZWtAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6Ik1hcmNlbG8gZGUgRnJlaXRhcyIsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbSIsIm5hbWUiOiJNYXJjZWxvIGRlIEZyZWl0YXMiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMS2phOUZjaGdYeU04bUJROFdYY0M2YTNLMnlVT3NjYTBpcVhQVThDOE02LVZPUTlKU0NRPXM5Ni1jIiwicHJvdmlkZXJfaWQiOiIxMTIyMTY1Mjg1ODAyNzQxMzM2OTkiLCJzdWIiOiIxMTIyMTY1Mjg1ODAyNzQxMzM2OTkifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvYXV0aCIsInRpbWVzdGFtcCI6MTc3MjczMDQ2NH1dLCJzZXNzaW9uX2lkIjoiN2RhMTUyYTEtNTVkOC00MmI0LWJkYTMtYThjMjdlNjQ3Y2MyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.kqBHtc-NKW8LpVbOcD0A7HnOXVpNrh1f14ANq2SIkdjVOXDquqWfdjZ_9JupqAY63cCxwSBRRFhHqVbZIvCMSw'
};

fetch(url, { headers })
    .then(res => res.json())
    .then(data => {
        console.log("Returned profiles:", JSON.stringify(data, null, 2));
    })
    .catch(console.error);
